### ISSUE TITLE
Guns are no longer the answer in the face of a liberty-denying oppressor.

### ISSUE THREAD

**Issue by HashRocketSyntax** [JesseKPhillips/USA-Constitution#5]
> A well regulated militia, being necessary to the security of a free state, the right of the people to keep and bear arms, shall not be infringed.

- A militia is no longer needed in order to ensure that the American experiment of democracy makes it to fruition.
- Modern weaponry is ridiculously OP in comparison to the muskets present at the time of original post. https://youtu.be/g62m7yOhgRY?t=33
- The mentally ill townsfolk and brigands keep killing lots of other townsfolk.

If you read the biographies about the people that wrote this document, they almost looked at it as a temporary means to get the nation started in the right direction, and they intentionally made it ready to evolve to suit the needs of the people. To put things in perspective, they were redoing the Articles of Confederation that were only finished in 1781.

Frankly, I think they would be appalled in our lack of democratic participation if they found out that we are not keeping it up to date.

**Perhaps the solution is two-fold:**
1. The people have the right to use appropriate weapons to hunt and protect themselves.
2. Revise the "right to assemble" in order to allow people to self-organize to resist oppressors.

**Comment by j-f1** [comment]
> While the master branch shall remain the actual edits to the Constitution, feel free to propose a new branch that include changes you'd like to express. I'll arbitrarily evaluate if it is suitable to be added. One idea might be to change the Constitution to clearly state the powers the government is executing with.
>
>Keep in mind this is not a formal platform to establish Constitutional changes.

**Comment by bdunbar** [comment]
`The right of the people to keep and bear arms, shall not be infringed.`

Done.

**Comment by crojasd00** [comment]
If the 2nd amendment only covers muskets and other weaponry present in the ear, then the freedom of speech should only apply to verbal speech, quilt and ink written letters and books made with a printing press.

**Comment by komali2** [comment]
Performance analysis compared to other solutions makes this entire section questionable. Suggest we adopt solutions from other projects that have evidence of working, i.e. Australia, UK, etc.

**Comment by Gabrielmtn** [comment]
> ```
> A well regulated militia, being necessary to the security of a free state, the right of the people to keep and bear arms, shall not be infringed.
> ```

Before we set out on enhancing or refactoring, we should first clean up the current interpretation's implementation. We should take an audit of:

- How well regulated are our Militias? 
- How much state security does our training/ownership process secure for us at present? 
- Do our current public health safety measures come anywhere near to infringing on rights? 

All of these cases are possible examples of poorly optimized implementations, but providing updates to something which isn't really being used properly in the first place sounds more like repairs of legal debt built up over the years, not the original feature.

**Comment by soulofmischief** [comment]
Which commit brought the American experiment of democracy to fruition? I'm having trouble finding it. Last time I checked, the system was highly unstable, prone to race conditions and full of legacy and closed-source modules.

From what I understand, we are all in agreement that there has been trouble within the project leadership for some time now, so perhaps we should label this as blocked for now.

**Comment by HashRocketSyntax** [comment]
@soulofmischief we successfully maintained independence, influence of foreign powers, and made it through a civil war.

**Comment by HashRocketSyntax** [comment]
@crojasd00 I'd argue that press was more powerful in the past because it is so diluted and dispersed now. Franklin held influence because everyone read his paper.

**Comment by pkallos** [comment]
> because media is so decentralized now

https://www.ptolemy3.com/essays/corporate-media-oligopoly

**Comment by varenc** [comment]
As a meta point, this is why we need to enforce better documentation processes in the future! The old devs just dumped this code on us and bounced leaving us to puzzle over it. 

With all the big systems already built, all our open roles are mainly about maintenance and building for niche users. This leads to a slow decline in our hiring bar and the current devs could really use so better docs, or at least a few code comments! In the future, we need clearer documentation practices to explain why a system is set up the way it is.  In this particular piece of code, the `well-regulated militia` reference is pretty confusing to me.

I know some might think a full re-write is tempting but with so many system interdependences and legacy users it's just too massive an undertaking.

**Comment by HashRocketSyntax** [comment]
@bdunbar 
> A well-regulated National Guard and Coast Guard are necessary to ensure the security of a free state.

Done.

Ingrained in the mindset of the authors was an inherent distrust of the people to do what is in their best interest of both themselves and the nation. This stems from (a) the fickleness they observed in the Revolutionary War and (b) the admiration they held for greco-roman statesmen like Cicero who viewed feared and loved the mob. These men had the wisdom to preface this right with an explanation so that it would not become a simple black and white binary. Yet, seeing the repeated atrocities we have wrecked with it, you are ready to make the situation even worse.

**Comment by lazear** [comment]
> > ```
> > A well regulated militia, being necessary to the security of a free state, the right of the people to keep and bear arms, shall not be infringed.
> > ```
> 
> Before we set out on enhancing or refactoring, we should first clean up the current interpretation's implementation. We should take an audit of:
> 
> * How well regulated are our Militias?

One might wish to examine the historical context of the phrase "well regulated" in order to understand the Framer's intent.  A quick google search will lead you to numerous examples, such as https://www.constitution.org/cons/wellregu.htm or https://constitutioncenter.org/images/uploads/news/CNN_Aug_11.pdf

> "Well-regulated in the 18th century tended to be something like well-organized, well-armed,
> well-disciplined," says Rakove. "It didn't mean 'regulation' in the sense that we use it now, in
> that it's not about the regulatory state. There's been nuance there. It means the militia was
> in an effective shape to fight."
> - Jack Rakove, professor of political science and law at Stanford 

Furthermore, you can simply remove the first clause of the amendment to get to the core of the matter: "The right of the people to keep and bear arms shall not be infringed". A strikingly clear piece of legislation.

**Comment by HashRocketSyntax** [comment]
@Gabrielmtn @lazear PA militia had their act together while others did not, that's all it's about.

You are making it about the 'what' and not the 'why.'

**Comment by soulofmischief** [comment]
@HashRocketSyntax 

> If you read the biographies about the people that wrote this document, they almost looked at it as a temporary means to get the nation started in the right direction

I'm not sure you understand what the Constitution was about. It wasn't written so that it could be unwritten a handful of centuries later.

**Comment by HashRocketSyntax** [comment]
@soulofmischief 
> The question Whether one generation of men has a right to bind another, seems never to have been started either on this or our side of[1] the water. Yet it is a question of such consequences as not only to merit decision, but place also, among the fundamental principles of every government. The course of reflection in which we are immersed here on the elementary principles of society has presented this question to my mind; and that no such obligation can be so transmitted I think very capable of proof.—I set out on this ground, which I suppose to be self evident, ‘that the earth belongs in usufruct to the living’:[2] that the dead have neither powers nor rights over it. - Thomas Jefferson to James Madison

**Comment by piedoom** [comment]
In favor of removing the 2nd amendment all together. Will likely reduce maintenance burden.

**Comment by codrcodz** [comment]
Looks like one of the original devs explained this pretty well in the mailing list during the RFC period. Here is a copy:

https://avalon.law.yale.edu/18th_century/fed46.asp

According to this, he and some of the other devs thought that the best defense against an out of control corporate headquarters was to make sure that both regional headquarters AND individual devs had the tools they needed to forcibly eject the c-level execs and the board if needed.

I think we should keep it how it is. I know it seems unlikely that corporate or even local leadership would do something that warrant it, but you never know...

- https://en.m.wikipedia.org/wiki/Tulsa_race_riot
- https://en.m.wikipedia.org/wiki/Kent_State_shootings
- https://en.m.wikipedia.org/wiki/Missouri_Executive_Order_44
- https://en.m.wikipedia.org/wiki/Indian_removal
- https://en.m.wikipedia.org/wiki/Battle_of_Gonzales

**Comment by JesseKPhillips** [comment]
The constitution is a living document and is expected to be modified with the times. When making modifications it is important to remember that current time does include what may be an outcome of the future. 

It is important to remember that removing or modifying this entry does not change anything. Since the constitution is a contract of granted power this entry only serves as a reminder that the granted powers are limited.

Considering the historical context and fear of possible future, I do not believe that today has sufficiently proven that those fears are invalid for our future. Leaving me to believe it is best to remain in the same self protection rules. 

Other implementations have chosen and survived with different rules. However it is not possible to control for all the variables. Geographical differences across a large land mass. We do not want a repeat of Internet Explorer where we remove competing implementations allowing all nations to only measure success against its own implementation.

**Comment by maltenuhn** [comment]
I thought we intended for these to be immutable... You could open a new issue (we have an `amendment` template somewhere you can use), but I know that the approval process is slow and somewhat opaque, a lot of non-contributors tend to come out of the woodwork and downvote things. 

There _is_ a clever way around this, you can simply commit a new interpreter. I know that feels a bit hacky, but the community has already managed to do this with the commerce clause function when we wanted to use it stop the discrimination attacks).

One caveat with this approach: the interpreter lives in a different repo, and its code is ~sometimes esoteric~ quite hard to read; if you think this repo has a lot of legacy code you'll be in for a surprise. Also it _is_ pretty hard to become an approved contributor. You usually start out creating contributions on the  vNext branches, maybe a handful of them get merged to master. 

Once you _are_ among those elite few, you just need a majority of the others to vote for your PR. That said, these days interpreter changes are pretty limited in scope, because otherwise none of the contributors agree on them...

(Apologies, I got carried away...)

**Comment by soulofmischief** [comment]
@HashRocketSyntax So we want to use the Whiskey Rebellion as an example?

https://en.wikipedia.org/wiki/Whiskey_Rebellion#Legacy

> The Washington administration's suppression of the Whiskey Rebellion met with widespread popular approval.[116] The episode demonstrated that the new national government had the willingness and ability to suppress violent resistance to its laws . . . 

> Federalists believed that the government was sovereign because it had been established by the people; radical protest actions were permissible during the American Revolution but were no longer legitimate, in their thinking. But the Whiskey Rebels and their defenders believed that the Revolution had established the people as a "collective sovereign", and the people had the collective right to change or challenge the government through extra-constitutional means.

You are in this context a Federalist, believing the time for revolution is over, and that a nation is its government, and I am a Whiskey Rebel, who considers a nation to be comprised of its people, ready to whip the government back into shape if need be. That's what this comes down to. 

Have you actually read the Federalist Papers? Did you know that they were against the Bill of Rights? The entire Federalist mentality was authoritarian and against the spirit of the revolution. [Just check this section on wikipedia dealing with its controversial judicial use](https://en.wikipedia.org/wiki/The_Federalist_Papers#Judicial_use). If it has shaky grounds in judicial law, it has even shakier grounds in extra-judicial law a.k.a. the social court of unresearched opinions.

Lately I see people try to (whether they realize it or not) promote Federalist values and point to Federalist literature as evidence to the mentality of *all* of our founding fathers at the time. Don't forget most of these men were old white slave owners. If we're taking down statutes of Robert E. Lee, why are we listening to James Madison?

**Comment by HashRocketSyntax** [comment]
@soulofmischief Anti-Federalists defended the expansion of slavery to the point of civil war. When founding the nation, Federalists knew the abolition of slavery was inevitable, but they believed it could not be addressed at that time because it would have prevented the nation from unifying. It is sad that GW failed to free his slaves in the many years post-war, during his presidency, and after.

Yes, I am a Federalist in this sense. The majority of people are uneducated, selfish, and violent - firearms is a great example.

**Comment by maltenuhn** [comment]
And while we're on the topic: it's also important to remember that both the Constitution and the Bill of Rights were written before it was clear how they would be enforced (judicial review, "unconstitutional" decisions by our Supreme Court), if & how they would bind state governments (the ones giving up power here, after all).

So at that time, when you asked yourself "should we write down rights the people have" you also were puzzling over things like this - which partially explains some of the awkward wording:

- If we write them down, does that mean the government of the day interpret that to mean '...and the people have _no others_'? But if we don't, will the government interpret that to mean 'no rights for you, citizen'?
- If we dont' write them down:  will _state_ governments simply pass laws ignoring them? (Btw it wasn't even agreed upon that these _would_ apply to states until the 1920s - in fact, [Barron vs Baltimore](https://en.wikipedia.org/wiki/Barron_v._Baltimore) (1833) explicitly said they don't (!). And could  _Congress_  pass laws that restrict those freedoms later (like the English Parliament could) -  even if right now we all agree rights not assigned to the government are reserved for the people?

**Comment by HashRocketSyntax** [comment]
@codrcodz Tulsa race riots, are you kidding me?! That's perhaps the best example in favor of gun control! Racist 'ethnic group of citizens 1' with guns kill tons of 'ethnic group of citizens 2.'

**Comment by Flushot** [comment]
Apologies for the more serious note, but I saw a few comments by @HashRocketSyntax that I wanted to address:

> A militia is no longer needed in order to ensure that the American experiment of democracy makes it to fruition.

Your statement presupposes that a militia (being necessary to the security a free state) was a temporary thing, and that democracy would never fall to tyranny once bootstrapped.

A better example of armed citizens rising up against tyranny here in the US would be the [Battle of Athens](https://en.wikipedia.org/wiki/Battle_of_Athens_(1946)), which happened only 73 years ago.

Aspiring tyrants certainly make it a point to disarm the non-military populace that keep could them in check, which is exactly what happened in China (Mao), Germany/Austria (Hitler), and Venezuela (Maduro). In this non-utopian world, why wouldn't history repeat itself?

> Modern weaponry is ridiculously OP in comparison to the muskets present at the time of original post.

Aside from a trite remark about modern media being ridiculously OP in comparison to when the 1st amendment was written, what about these examples of weapons that already existed at the time?

- Cannons: These were legal to own and caused mass casualties with grapeshot and exploding balls.
- Puckle Gun (1718): Machine gun with a rotating barrel.
- Belton Flintlock (1777): Capable of firing up to either 16 or 20 rounds within either 16, 10, or 5 seconds.
- Girandoni Air Rifle (1779): Had a 20 round magazine.

I see this argument brought up a lot. Can you cite where the founders wanted to limit a weapon's effectiveness to muskets, given the technological advancements (and arguably more OP weapons than today's sporting rifles, such as cannons) we had at the time? It seems like quite a leap.

> All your other examples are essentially about non-citizen/ autonomous groups that the rights don't legally pertain to.

I don't see how the Kent State Shootings example (i.e. unarmed students protesting) qualifies as a non-citizen group that rights don't pertain to, nor do I see how an illegal executive order in Missouri to exterminate mormons can get a pass either. Perhaps I'm missing some context you can clarify?

**Comment by JesseKPhillips** [comment]
@maltenuhn I think your analogy about changing interpreter to modify the program is so right. We don't change "hello world" but reinterpret it to mean "good bye landmass"

We then live on case law because there is no way to clarify.

**Comment by soulofmischief** [comment]
@HashRocketSyntax Slavery is the only thing the Federalists and I agree on. However, James Madison, one of the original Publius (Federalist Paper authors) was in fact a slaveholder and kept his slaves until death, viewing slavery as a necessary part of the economy.

So we can cherry-pick the values of individuals all we want, but we're specifically talking about the 2nd amendment so it would be prudent to remain on topic.

I'm stumped as to how you reconcile situations like the Hong Kong rebellion and the ongoing Kurdish genocide with this concept of governments evolving past the point of tyranny. These countries are much older than the US and yet in such turmoil. Your short life precludes you from seeing the larger historical patterns.

**Comment by The45Guy177y** [comment]
This article is written by a liberal hack obviously. The 2nd ammendment for 1 was put in place so the people would have a means to fight the government should it become tyrannical. 2ndly You are aware that a standing army is unconstitutional for 1 and 2 this military is run by corperations like Exxon Mobile. Man people get me when they start flapping incoherently. Dive deep into American history and learn something before you post crap like this because the other uneducated people like you all think your some kind of genius now. And Australia nor the UK worked. Violent crimes went sky high in Australia after the ban and the UK has more heavily armed criminals than ever in its history because criminals dont obey laws and dont buy guns legally thats why thier criminals.

**Comment by wolfebrian2120** [comment]
> @soulofmischief
> 
> > The question Whether one generation of men has a right to bind another, seems never to have been started either on this or our side of[1] the water. Yet it is a question of such consequences as not only to merit decision, but place also, among the fundamental principles of every government. The course of reflection in which we are immersed here on the elementary principles of society has presented this question to my mind; and that no such obligation can be so transmitted I think very capable of proof.—I set out on this ground, which I suppose to be self evident, ‘that the earth belongs in usufruct to the living’:[2] that the dead have neither powers nor rights over it. - Thomas Jefferson to James Madison
> 
> https://en.wikipedia.org/wiki/Living_Constitution
> 
> I could make arguments about how quickly they regretted this amendment when shutting down the Whiskey Rebellion and what it really means, however that's besides the point. Let's stop arguing about what it meant and determine what it means to us in a revision.

I think you misunderstand how the feature of amending the code works. While yes the code can change, While we are not eternally bound by the rules that the founders put in place. We cannot just rip out sections of it because we don't like the way it was written. Your arguing that this piece is no longer relevant.  You need to pass an amendment and you can't do that with simple majorities. You have to convince a lot of people to change it.

> @HashRocketSyntax 
> Perhaps the solution is two-fold:
> 1. The people have the right to use appropriate weapons to hunt and protect themselves.

Not sure where in the second amendment it mentions a right to hunt. Not sure why you need to add this, no one seems to be questioning the ability to hunt. The protection item is interesting here. Who decided what appropriate weapons are? I guess your more worried about the types of weapons available rather than the people who use them. I suggest you propose something that deals with dangerous individuals rather than regulating innocent people.

> 2. Revise the "right to assemble" in order to allow people to self-organize to resist oppressors.

Right to assembly is in the first amendment. I don't think you've proposed changing that one. 2nd Amendment is in regards to assembling a militia for the purpose of maintaining a free state. It doesn't necessarily have to be state sanctioned or approved, thats kind of the point of a militia, otherwise it would be an army. 

The current feature sett covers both of these features your after quite well, simply because it recognizes the right of  the people to keep and bear arms. Arms being weapons of any kind to be used to defend their own freedom.

I am also not convinced that changing it to your proposal will have the desired affect you seek to achieve.

**Comment by Schwarttzy** [comment]
Debate all you want, but what you don't understand are the words "Come and take it!"

**Comment by HashRocketSyntax** [comment]
@soulofmischief actually, I wrote my college application essays on Kurdistan over a decade ago. 

Really proud of Hong Kong. The reconciliation that I am struggling with now is that non-violent resistance like Gandhi is much more challenging if the persecuted group is not large enough to put a dent in the economy. 

I'm not against violence in the face of an oppressor when it's the last resort. I've spoken with Jesse Jackson on this matter.

**Comment by soulofmischief** [comment]
@HashRocketSyntax

> The reconciliation that I am struggling with now is that non-violent resistance like Gandhi is much more challenging if the persecuted group is not large enough to put a dent in the economy via non-participation.

This ignores the fact that, parallel to Ghandi, the people actually doing the work to drive out foreign influence and secure the Indian borders were the Hindu revolutionaries, muskets and all.

 And why do *you* get the authority to decide when guns are a "last resort"? If Americans have already been stripped of their right to bear arms in the face of tyranny, where the heck do we get our guns when the "last resort" has arrived? The *entire point* of the second amendment is that you can't relinquish control of your right to bear arms in the first place, because you will never get it back. By design, government power is a ratchet.

Your argument holds no water because it's fully of contradictory holes. You haven't even taken it to its logical conclusion, you're either being intentionally deceptive or ignorant of the fact that guns aren't magically going to appear in our lap when our government pulls your last straw.

**Comment by HashRocketSyntax** [comment]
@soulofmischief in wielding a gun, one is essentially saying that they are willing to kill someone if that's what it comes to. how is potentially killing someone not a last alternative? what other alternatives are beyond that?

I intentionally haven't thought the argument all the way through because I wanted to encourage discussion.

Not sure what boot you are referring to or why you or why you feel a need to bring this up.

**Comment by piedoom** [comment]
not sure why you closed, still experiencing this issue. saw someone with a gun the other day.

**Comment by JesseKPhillips** [comment]
@piedoom sorry

"It is important to remember that removing or modifying this entry does not change anything. Since the constitution is a contract of granted power this entry only serves as a reminder that the granted powers are limited."
